### ISSUE TITLE
Support TypeScript declarations

### ISSUE THREAD

**Issue by ceilfors** [laconiajs/laconia#35]
**User Story**

As a user of Laconia,
I would like to be able to use Laconia without looking at its documentation
And fully rely on my IDE
So that I can be more productive at work

**Acceptance Criteria**
- *.d.ts files are generated for every packages
- Current API references at laconiajs.io must be generated from the same source

**Subtasks**

- [x] core
- [ ] adapter
- [ ] adapter-api
- [ ] event
- [ ] invoker
- [ ] config
- [ ] batch
- [ ] middleware-lambda-warmer
- [ ] middleware-serverless-plugin-warmupserverless-plugin-warmup
- [x] include `tsc` in build
- [x] enable ts-check to acceptance-test

**Comment by ceilfors** [comment]
Options that are currently available:

1.  Fully port to TypeScript
    - Use case: next.js
    - Pros: Source and TS definition will be in sync
    - Cons: Reduce inclusivity to the community (people might not be comfortable contributing in TypeScript)
2. Generate *.d.ts files and stay on JavaScript
    - Use case: vue.js (there are tests too!)
    - Pros: Increased inclusivity for contributors
    - Cons: Source and TS definition might go out of sync

Approach for option 1 is pretty straight forward, rename .js to .ts, fix all errors.

Approach for option 2:

1. By hand
    - No need for explanation, write it manually

2. By JSDocs
    - Can be as powerful as *.d.ts files even without generating one in VS Code

**Comment by Rob-H** [comment]
I am leaning towards writing in typescript, however I am biased 😄 . For option 2 how do you mean vue.js has tests?

**Comment by ceilfors** [comment]
@Rob-H I'm actually interested to port, but the effort vs benefit seems far too great for the use case of just for this particular story.

On vue.js test, I haven't looked into details, but this might mitigate the risk of d.ts and .js to go out of sync: 
- https://github.com/vuejs/vue/tree/dev/types/test
- https://github.com/vuejs/vue/blob/dev/package.json#L36

Also apparently next.js is not fully ported to TS, so I can't actually find a good use case for packages that have fully ported to TS.

Additionally, one thing I like about creating d.ts by hand is that file will actually be Laconia API living documentation, sitting in one place. I won't get the same benefit if I generate the d.ts via TypeScript nor JSDocs. Thoughts?

**Comment by Rob-H** [comment]
Ah ok, so for vue their tests are actually just compiling some example typescript code. That's quite nice. 

I would argue that you would get the same benefits as you would with writing them manually as with the other options still generate the d.ts files, whether that documentation is hand written or generated shouldn't matter really. I guess it's up to you if you would rather the API description is in one place or closer to the code.

**Comment by ceilfors** [comment]
Thanks for your feedback so far @Rob-H! I've been doing a small research and I think we should go with JS + ts.d for now as I can't lose *Community inclusivity* as of today. I envision to keep this project free and community driven. I also would like to think that the declaration files that we produce will be an iteration towards porting to TypeScript. So it's a win-win.

Please let me know if you foresee red flags with this route, otherwise I'll proceed with the development of this route!

### Comparison table

| Requirement                       | JS + JSDoc | Port to TS | JS + ts.d | Notes                                                                            |
| --------------------------------- | ---------- | ---------- | --------- | -------------------------------------------------------------------------------- |
| Community inclusivity             | 4          | 2          | 5         | [Popularity](https://insights.stackoverflow.com/survey/2019): JS 67.8%, TS 21.2% |
| Explicit public API visibility    | 2          | 5          | 5         | How easy it is to determine which API are public                                 |
| Docusaurus integration            | 2          | 4          | 4         |                                                                                  |
| Enforce type definition           | 1          | 5          | 5         | It's very easy to miss type in JSDoc, which is the purpose of this issue         |
| Unlikelihood of docs divergence   | 4          | 5          | 2         | The closer to the source code the better                                         |
| Effort to cover entire repository | 4          | 1          | 4         | The easier to better.                                                            |
| **Total**                         | **17**     | **22**     | **25**    |                                                                                  |


### Research notes for JS + d.ts

#### Unlikelihood of docs divergence

To mitigate the risk of the divergence of source code and documentation, the following will be done:
- `// @ts-check` will be enabled in: laconia-acceptance-test source, public API level unit tests
- Execute `tsc` with `--allowJs` to enforce type checking those files enabled with `// @ts-check`

Example tsconfig.json:
```
{
  "compilerOptions": {
    "allowJs": true,
    "noEmit": true,
    "strict": true
  },
  "include": ["packages/laconia-core/**/*"],
  "exclude": ["node_modules"]
}
```

#### Docusaurus Integration

Documentations can be generated easily with the following packages:
- typedoc
- typedoc-plugin-markdown

Commands that we need to execute:
```
npx typedoc packages --theme markdown --out tsdocusaurus --includeDeclarations --exclude '**/+(*test*|node_modules)/**'  --mode file --mdDocusaurus
```

**Comment by ceilfors** [comment]
This issue has been broken down to multiple issues and tied by a milestone. See referenced issues above.

**Comment by ceilfors** [comment]
@all-contributors please add Rob-H for ideas

**Comment by ceilfors** [comment]
@all-contributors please add @Rob-H for ideas
